apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
  labels:
    app: bank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      name: bankapp
      labels:
        app: bank
    spec:
      containers:
      - name: bankapp
        image: carmichaelc09/wedding:v1
        ports:
        - containerPort: 8080
---
#creating a service for this deployment
kind: Service
apiVersion: v1
metadata:
  name: bankv3
spec:
  selector:
    app: bank
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    #nodePort: 31000
